php:
  build: ./
  links:
    - db
  ports:
    - 80:80
  volumes:
    - ./www/:/var/www/html/

db:
  image: mariadb:10.7.1
  environment:
    MYSQL_ROOT_PASSWORD: 9494688476752f693ffb6e48
  volumes:
    - ./setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql

pma:
  image: phpmyadmin/phpmyadmin:5.1.1
  links:
    - db
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 9494688476752f693ffb6e48
